[workspace]
members = ["vibe-renderer"]
resolver = "2"

# [dependencies]

# tracing = "0.1"
# tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# reqwest = { version = "0.12", default-features = false, features = [
#   "rustls-tls",
#   "blocking",
# ] }

# wayland-client = "0.31"
# wayland-backend = { version = "0.3", features = ["client_system"] }
# smithay-client-toolkit = "0.19"

# xdg = "2.5"
# toml = { version = "0.8", features = ["parse", "display"] }
# serde = { version = "1", features = ["derive"] }

[profile.release-lto]
inherits = "release"
codegen-units = 1
lto = true
