[package]
name = "vibe"
version = "0.0.1"
edition = "2021"
authors = ["TornaxO7 <tornax@pm.me>"]
description = "A desktop music visualizer"
license = "GPL-2.0"
repository = "https://github.com/TornaxO7/vibe"

[dependencies]
raw-window-handle = "0.6"
smithay-client-toolkit = "0.19"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
wayland-client = "0.31"
wgpu = "24.0"
xdg = "2.5"

[profile.release-lto]
inherits = "release"
codegen-units = 1
lto = true
