[workspace]
members = ["vibe-renderer", "vibe", "vibe-audio"]
resolver = "2"

[workspace.dependencies]
anyhow = "1"
wgpu = { version = "26.0", default-features = false, features = [
  # from the default features
  "gles",
  "parking_lot",
  "std",
  "vulkan",
  "wgsl",

  # extra features
  "serde",
  "glsl",
  "naga-ir",
] }

serde = { version = "1", features = ["derive"] }
tracing = "0.1"
thiserror = "2"
cgmath = { version = "0.18", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
vibe-audio = { path = "./vibe-audio" }
image = "0.25"

[profile.release-lto]
inherits = "release"
codegen-units = 1
lto = true
