[workspace]
members = ["dreamer-daemon"]
resolver = "2"

[workspace.dependencies]
ron = "0.8"
serde = { version = "1", features = ["derive"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

xdg = "2.5"

[profile.release-lto]
inherits = "release"
codegen-units = 1
lto = true
