[package]
name = "dreamer"
version = "0.1.0"
edition = "2021"

[dependencies]
ron.workspace = true
serde.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

xdg.workspace = true

smithay-client-toolkit = "0.19"
wgpu = "24.0"
pollster = "0.4"
