[package]
name = "vibe-daemon"
version = "0.0.1"
edition = "2021"
authors = ["TornaxO7 <tornax@pm.me>"]
description = "A desktop music visualizer."
license = "GPL-2.0"
repository = "https://github.com/TornaxO7/vibe-daemon"

[dependencies]
anyhow = "1"
raw-window-handle = "0.6"
