[package]
name = "vibe-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
toml.workspace = true
serde.workspace = true
shady.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

xdg.workspace = true

anyhow.workspace = true

smithay-client-toolkit = "0.19"
wayland-backend = { version = "0.3", features = ["client_system"] }

wgpu = "24.0"
pollster = "0.4"
raw-window-handle = "0.6"
